import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case english = "en"
    case hindi = "hi"
    case hinglish = "hinglish"
    case spanish = "es"
    case french = "fr"
    case tamil = "ta"
    case telugu = "te"
    case bengali = "bn"
    
    var id: String { rawValue }
    
    var displayName: String {
        switch self {
        case .english: return "English"
        case .hindi: return "हिन्दी (Hindi)"
        case .hinglish: return "Hinglish (Everyday Hindi)"
        case .spanish: return "Español (Spanish)"
        case .french: return "Français (French)"
        case .tamil: return "தமிழ் (Tamil)"
        case .telugu: return "తెలుగు (Telugu)"
        case .bengali: return "বাংলা (Bengali)"
        }
    }
    
    var shortName: String {
        switch self {
        case .english: return "English"
        case .hindi: return "हिन्दी"
        case .hinglish: return "Hinglish"
        case .spanish: return "Español"
        case .french: return "Français"
        case .tamil: return "தமிழ்"
        case .telugu: return "తెలుగు"
        case .bengali: return "বাংলা"
        }
    }
    
    var flag: String {
        switch self {
        case .english: return "🇬🇧"
        case .hindi: return "🇮🇳"
        case .hinglish: return "🇮🇳"
        case .spanish: return "🇪🇸"
        case .french: return "🇫🇷"
        case .tamil: return "🇮🇳"
        case .telugu: return "🇮🇳"
        case .bengali: return "🇮🇳"
        }
    }
}

class LanguageManager: ObservableObject {
    static let shared = LanguageManager()
    
    @AppStorage("chefpocket_app_language") var currentLanguage: AppLanguage = .english {
        didSet {
            objectWillChange.send()
        }
    }
    
    // MARK: - Localized String Getter
    func t(_ key: String) -> String {
        guard let langDict = translations[currentLanguage.rawValue] ?? translations[AppLanguage.english.rawValue],
              let text = langDict[key] else {
            return translations[AppLanguage.english.rawValue]?[key] ?? key
        }
        return text
    }
    
    // MARK: - Translations Dictionary
    private let translations: [String: [String: String]] = [
        // 1. ENGLISH
        "en": [
            "tab_cookbook": "Cookbook",
            "tab_thali": "Thali Planner",
            "tab_groceries": "Sabzi Mandi",
            "tab_cookmode": "Cook Mode",
            "scope_curated": "Curated (400+)",
            "scope_my_kitchen": "My Kitchen",
            "diet_all": "All",
            "diet_veg": "Veg",
            "diet_non_veg": "Non-Veg",
            "search_placeholder": "Search 400+ dishes, ingredients, cuisines...",
            "filter_cuisine": "Cuisine",
            "filter_meal": "Meal",
            "filter_category": "Category",
            "filter_reset": "Reset",
            "aaj_kya_banau": "Aaj Kya Banau?",
            "aaj_kya_banau_sub": "Can't decide? Tap for an instant meal suggestion.",
            "aaj_kya_banau_btn": "Surprise Me!",
            "btn_import_video": "Import Recipe from Reel / Shorts",
            "btn_add_manual": "Add Recipe Manually",
            "ingredients": "Ingredients",
            "instructions": "Cooking Instructions",
            "add_all_to_groceries": "Add All to List",
            "share_recipe": "Share Recipe via WhatsApp & More",
            "delete_recipe": "Delete Recipe",
            "confirm_delete_title": "Delete Recipe?",
            "confirm_delete_msg": "Are you sure you want to delete this custom recipe? This action cannot be undone.",
            "cancel": "Cancel",
            "delete": "Delete",
            "already_in_kitchen": "Recipe Already in Kitchen",
            "already_in_kitchen_msg": "This video recipe is already saved in your kitchen.",
            "thali_title": "Daily Thali Planner",
            "thali_subtitle": "Balanced Indian dining: Dal, Sabzi & Phulkas for complete nutrition.",
            "thali_suggest": "Suggest Thali",
            "thali_add_all": "Add Entire Thali to Sabzi Mandi",
            "mandi_title": "Sabzi Mandi",
            "mandi_empty": "Your Sabzi Mandi List is Empty",
            "mandi_empty_sub": "Add items from your favorite recipes or add custom groceries below!",
            "clear_checked": "Clear Checked",
            "add_item": "Add Item",
            "cookmode_title": "Smart Cook Mode",
            "whistle_counter": "Pressure Cooker Whistle Counter",
            "tap_whistle": "TAP WHISTLE",
            "whistle_done": "Target reached! Turn off flame.",
            "waiting_whistle": "Waiting for cooker whistle...",
            "desi_timers": "Desi Kitchen Quick Timers",
            "countertop_reader": "Countertop Step Reader",
            "step_of": "Step %d of %d",
            "next_step": "Next Step",
            "prev_step": "Previous",
            "finished_cooking": "Finished Cooking! 🎉",
            "settings": "Profile & Settings",
            "theme": "Appearance & Theme",
            "theme_system": "System",
            "theme_light": "Light",
            "theme_dark": "Dark",
            "language": "App Language",
            "cloud_sync": "Cloud Sync (Google Account)",
            "sync_now": "Sync Now",
            "synced_status": "All kitchen data synced with Google Account",
            "logout": "Log Out"
        ],
        
        // 2. HINDI (हिन्दी)
        "hi": [
            "tab_cookbook": "कुकबुक",
            "tab_thali": "थाली प्लानर",
            "tab_groceries": "सब्ज़ी मंडी",
            "tab_cookmode": "कुक मोड",
            "scope_curated": "इनबिल्ट रेसिपीज़ (400+)",
            "scope_my_kitchen": "मेरी रसोई",
            "diet_all": "सभी",
            "diet_veg": "शाकाहारी (Veg)",
            "diet_non_veg": "मांसाहारी (Non-Veg)",
            "search_placeholder": "व्यंजन, पनीर, चिकन, दाल या सामग्री खोजें...",
            "filter_cuisine": "व्यंजन शैली",
            "filter_meal": "भोजन समय",
            "filter_category": "श्रेणी",
            "filter_reset": "रीसेट",
            "aaj_kya_banau": "आज क्या बनाऊं?",
            "aaj_kya_banau_sub": "तय नहीं कर पा रहे? तुरंत स्वादिष्ट सुझाव पाएं।",
            "aaj_kya_banau_btn": "नया सुझाव!",
            "btn_import_video": "यूट्यूब या रील्स से रेसिपी निकालें",
            "btn_add_manual": "खुद की नई रेसिपी जोड़ें",
            "ingredients": "आवश्यक सामग्री",
            "instructions": "पकाने की विधि",
            "add_all_to_groceries": "सब्ज़ी मंडी में जोड़ें",
            "share_recipe": "रेसिपी व्हाट्सएप व दोस्तों को भेजें",
            "delete_recipe": "रेसिपी हटाएं",
            "confirm_delete_title": "क्या यह रेसिपी हटाना चाहते हैं?",
            "confirm_delete_msg": "यह रेसिपी आपकी रसोई से हमेशा के लिए हट जाएगी।",
            "cancel": "रद्द करें",
            "delete": "हटाएं",
            "already_in_kitchen": "रेसिपी पहले से मौजूद है",
            "already_in_kitchen_msg": "यह वीडियो रेसिपी पहले से ही आपकी रसोई में सहेजी हुई है।",
            "thali_title": "दैनिक थाली प्लानर",
            "thali_subtitle": "संतुलित भारतीय भोजन: दाल, सूखी सब्ज़ी और रोटियों का संपूर्ण पोषण।",
            "thali_suggest": "थाली सुझाएं",
            "thali_add_all": "पूरी थाली सब्ज़ी मंडी में जोड़ें",
            "mandi_title": "सब्ज़ी मंडी",
            "mandi_empty": "आपकी सब्ज़ी मंडी सूची खाली है",
            "mandi_empty_sub": "रेसिपी से सामान जोड़ें या नीचे नया सामान लिखें!",
            "clear_checked": "खरीदा सामान हटाएं",
            "add_item": "सामान जोड़ें",
            "cookmode_title": "स्मार्ट कुक मोड",
            "whistle_counter": "कुकर सीटी काउंटर",
            "tap_whistle": "सीटी गिनें",
            "whistle_done": "सीटी पूरी हुई! गैस बंद करें।",
            "waiting_whistle": "कुकर की सीटी का इंतज़ार...",
            "desi_timers": "देसी रसोई टाइमर्स",
            "countertop_reader": "स्टेप-बाय-स्टेप कुकिंग",
            "step_of": "चरण %d / %d",
            "next_step": "अगला चरण",
            "prev_step": "पिछला",
            "finished_cooking": "खाना तैयार है! 🎉",
            "settings": "प्रोफाइल व सेटिंग्स",
            "theme": "थीम (डार्क / लाइट मोड)",
            "theme_system": "सिस्टम",
            "theme_light": "लाइट",
            "theme_dark": "डार्क",
            "language": "भाषा चुनें",
            "cloud_sync": "क्लाउड सिंक (Google खाता)",
            "sync_now": "अभी सिंक करें",
            "synced_status": "आपकी सभी रेसिपीज़ Google खाते से सुरक्षित हैं",
            "logout": "लॉग आउट"
        ],
        
        // 3. HINGLISH (Conversational Everyday Hindi)
        "hinglish": [
            "tab_cookbook": "Cookbook",
            "tab_thali": "Thali Planner",
            "tab_groceries": "Sabzi Mandi",
            "tab_cookmode": "Cook Mode",
            "scope_curated": "Inbuilt Recipes (400+)",
            "scope_my_kitchen": "Meri Kitchen",
            "diet_all": "Sab Dishes",
            "diet_veg": "Pure Veg",
            "diet_non_veg": "Non-Veg",
            "search_placeholder": "Paneer, chicken, dal, pasta search karo...",
            "filter_cuisine": "Cuisine",
            "filter_meal": "Meal Time",
            "filter_category": "Category",
            "filter_reset": "Reset",
            "aaj_kya_banau": "Aaj Kya Banau?",
            "aaj_kya_banau_sub": "Samajh nahi aa raha? Ek tap me mast suggestion lo.",
            "aaj_kya_banau_btn": "Spin Karo!",
            "btn_import_video": "Reels / Shorts se Recipe nikalo",
            "btn_add_manual": "Apni nayi Recipe likho",
            "ingredients": "Zaroori Samagri (Ingredients)",
            "instructions": "Banane ka Tareeka (Steps)",
            "add_all_to_groceries": "Sabzi Mandi me daalo",
            "share_recipe": "WhatsApp pe Share karo",
            "delete_recipe": "Recipe Delete karo",
            "confirm_delete_title": "Recipe delete karni hai?",
            "confirm_delete_msg": "Yeh recipe aapki kitchen se hamesha ke liye hat jayegi.",
            "cancel": "Cancel",
            "delete": "Delete",
            "already_in_kitchen": "Pehle se saved hai!",
            "already_in_kitchen_msg": "Yeh video recipe already aapki kitchen me save hai.",
            "thali_title": "Daily Thali Planner",
            "thali_subtitle": "Proper desi khana: Dal, Sabzi aur Garam Phulke.",
            "thali_suggest": "Suggest Thali",
            "thali_add_all": "Puri Thali Sabzi Mandi me bhejo",
            "mandi_title": "Sabzi Mandi",
            "mandi_empty": "Aapki Sabzi Mandi list khali hai",
            "mandi_empty_sub": "Recipes se ingredients add karo ya custom item likho!",
            "clear_checked": "Liya hua saaf karo",
            "add_item": "Item add karo",
            "cookmode_title": "Smart Cook Mode",
            "whistle_counter": "Pressure Cooker Whistle Counter",
            "tap_whistle": "WHISTLE TAP",
            "whistle_done": "Whistles complete! Gas band karo.",
            "waiting_whistle": "Cooker ki seeti ka wait...",
            "desi_timers": "Desi Kitchen Timers",
            "countertop_reader": "Kitchen Reader",
            "step_of": "Step %d of %d",
            "next_step": "Agla Step",
            "prev_step": "Pichhla",
            "finished_cooking": "Khana taiyaar hai! 🎉",
            "settings": "Profile & Settings",
            "theme": "Theme (Dark / Light Mode)",
            "theme_system": "System",
            "theme_light": "Light",
            "theme_dark": "Dark",
            "language": "App ki Bhasha",
            "cloud_sync": "Cloud Sync (Google Account)",
            "sync_now": "Sync Now",
            "synced_status": "Aapka data Google Account ke saath sync hai",
            "logout": "Log Out"
        ],
        
        // 4. SPANISH (Español)
        "es": [
            "tab_cookbook": "Recetario",
            "tab_thali": "Planificador Thali",
            "tab_groceries": "Lista de Compras",
            "tab_cookmode": "Modo Cocina",
            "scope_curated": "Recetas (400+)",
            "scope_my_kitchen": "Mi Cocina",
            "diet_all": "Todos",
            "diet_veg": "Vegetariano",
            "diet_non_veg": "No Vegetariano",
            "search_placeholder": "Buscar platos, ingredientes, cocina...",
            "filter_cuisine": "Cocina",
            "filter_meal": "Comida",
            "filter_category": "Categoría",
            "filter_reset": "Restablecer",
            "aaj_kya_banau": "¿Qué cocino hoy?",
            "aaj_kya_banau_sub": "¿No decides? Toca para una sugerencia instantánea.",
            "aaj_kya_banau_btn": "¡Soriéndeme!",
            "btn_import_video": "Importar desde Shorts / Reels",
            "btn_add_manual": "Añadir receta manual",
            "ingredients": "Ingredientes",
            "instructions": "Instrucciones de Cocina",
            "add_all_to_groceries": "Añadir todo a la lista",
            "share_recipe": "Compartir receta",
            "delete_recipe": "Eliminar receta",
            "confirm_delete_title": "¿Eliminar receta?",
            "confirm_delete_msg": "¿Estás seguro de eliminar esta receta?",
            "cancel": "Cancelar",
            "delete": "Eliminar",
            "already_in_kitchen": "Ya guardada en tu cocina",
            "already_in_kitchen_msg": "Esta receta en video ya está guardada.",
            "thali_title": "Planificador Thali",
            "thali_subtitle": "Comida india equilibrada y completa.",
            "thali_suggest": "Sugerir Thali",
            "thali_add_all": "Añadir Thali a compras",
            "mandi_title": "Lista de Compras",
            "mandi_empty": "Tu lista está vacía",
            "mandi_empty_sub": "Añade ingredientes desde tus recetas favoritas.",
            "clear_checked": "Limpiar comprados",
            "add_item": "Añadir artículo",
            "cookmode_title": "Modo Cocina",
            "whistle_counter": "Contador de Silbatos Olla",
            "tap_whistle": "SILBATO",
            "whistle_done": "¡Objetivo alcanzado! Apagar el fuego.",
            "waiting_whistle": "Esperando el silbato...",
            "desi_timers": "Temporizadores de Cocina",
            "countertop_reader": "Lector paso a paso",
            "step_of": "Paso %d de %d",
            "next_step": "Siguiente paso",
            "prev_step": "Anterior",
            "finished_cooking": "¡Cocina terminada! 🎉",
            "settings": "Perfil y Ajustes",
            "theme": "Tema (Claro / Oscuro)",
            "theme_system": "Sistema",
            "theme_light": "Claro",
            "theme_dark": "Oscuro",
            "language": "Idioma de la aplicación",
            "cloud_sync": "Sincronización en la nube",
            "sync_now": "Sincronizar ahora",
            "synced_status": "Datos sincronizados con Google",
            "logout": "Cerrar sesión"
        ],
        
        // 5. FRENCH (Français)
        "fr": [
            "tab_cookbook": "Livre de recettes",
            "tab_thali": "Planificateur Thali",
            "tab_groceries": "Liste de courses",
            "tab_cookmode": "Mode Cuisson",
            "scope_curated": "Recettes (400+)",
            "scope_my_kitchen": "Ma Cuisine",
            "diet_all": "Tous",
            "diet_veg": "Végétarien",
            "diet_non_veg": "Non-Végétarien",
            "search_placeholder": "Rechercher plats, ingrédients...",
            "filter_cuisine": "Cuisine",
            "filter_meal": "Repas",
            "filter_category": "Catégorie",
            "filter_reset": "Réinitialiser",
            "aaj_kya_banau": "Que cuisiner aujourd'hui ?",
            "aaj_kya_banau_sub": "Besoin d'inspiration ? Touchez pour une idée.",
            "aaj_kya_banau_btn": "Surprenez-moi !",
            "btn_import_video": "Importer depuis Reels / Shorts",
            "btn_add_manual": "Ajouter une recette",
            "ingredients": "Ingrédients",
            "instructions": "Instructions de préparation",
            "add_all_to_groceries": "Tout ajouter aux courses",
            "share_recipe": "Partager la recette",
            "delete_recipe": "Supprimer la recette",
            "confirm_delete_title": "Supprimer la recette ?",
            "confirm_delete_msg": "Êtes-vous sûr de vouloir supprimer cette recette ?",
            "cancel": "Annuler",
            "delete": "Supprimer",
            "already_in_kitchen": "Déjà enregistrée",
            "already_in_kitchen_msg": "Cette recette est déjà dans votre cuisine.",
            "thali_title": "Planificateur Thali",
            "thali_subtitle": "Repas indien équilibré et complet.",
            "thali_suggest": "Suggérer un Thali",
            "thali_add_all": "Ajouter le Thali aux courses",
            "mandi_title": "Liste de Courses",
            "mandi_empty": "Votre liste est vide",
            "mandi_empty_sub": "Ajoutez des ingrédients depuis vos recettes favorites.",
            "clear_checked": "Effacer cochés",
            "add_item": "Ajouter un article",
            "cookmode_title": "Mode Cuisson",
            "whistle_counter": "Compteur de sifflets cocotte",
            "tap_whistle": "SIFFLET",
            "whistle_done": "Objectif atteint ! Éteignez le feu.",
            "waiting_whistle": "En attente du sifflet...",
            "desi_timers": "Minuteurs de cuisine",
            "countertop_reader": "Guide étape par étape",
            "step_of": "Étape %d sur %d",
            "next_step": "Étape suivante",
            "prev_step": "Précédente",
            "finished_cooking": "Plat prêt ! 🎉",
            "settings": "Profil et Réglages",
            "theme": "Apparence (Clair / Sombre)",
            "theme_system": "Système",
            "theme_light": "Clair",
            "theme_dark": "Sombre",
            "language": "Langue",
            "cloud_sync": "Synchronisation Cloud",
            "sync_now": "Synchroniser",
            "synced_status": "Données synchronisées avec Google",
            "logout": "Se déconnecter"
        ],
        
        // 6. TAMIL (தமிழ்)
        "ta": [
            "tab_cookbook": "சமையல் புத்தகம்",
            "tab_thali": "தாலி பிளானர்",
            "tab_groceries": "காய்கறி சந்தை",
            "tab_cookmode": "சமையல் முறை",
            "scope_curated": "உள்ளமைக்கப்பட்டவை (400+)",
            "scope_my_kitchen": "என் சமையலறை",
            "diet_all": "அனைத்தும்",
            "diet_veg": "சைவம்",
            "diet_non_veg": "அசைவம்",
            "search_placeholder": "உணவுகள், பொருட்கள் தேடுங்கள்...",
            "filter_cuisine": "சமையல் வகை",
            "filter_meal": "உணவு நேரம்",
            "filter_category": "வகை",
            "filter_reset": "மீட்டமை",
            "aaj_kya_banau": "இன்று என்ன சமைப்பது?",
            "aaj_kya_banau_sub": "யோசிக்க முடியவில்லையா? உடனடி யோசனை பெறுங்கள்.",
            "aaj_kya_banau_btn": "பரிந்துரை செய்!",
            "btn_import_video": "ரீல்ஸ் / ஷார்ட்ஸிலிருந்து இறக்குமதி",
            "btn_add_manual": "புதிய செய்முறையை சேர்க்க",
            "ingredients": "தேவையான பொருட்கள்",
            "instructions": "சமைக்கும் முறை",
            "add_all_to_groceries": "சந்தைப் பட்டியலில் சேர்க்க",
            "share_recipe": "செய்முறையைப் பகிர்க",
            "delete_recipe": "செய்முறையை நீக்கு",
            "confirm_delete_title": "செய்முறையை நீக்கவா?",
            "confirm_delete_msg": "இந்த செய்முறை நிரந்தரமாக நீக்கப்படும்.",
            "cancel": "ரத்து",
            "delete": "நீக்கு",
            "already_in_kitchen": "ஏற்கனவே சேமிக்கப்பட்டுள்ளது",
            "already_in_kitchen_msg": "இந்த செய்முறை ஏற்கனவே உங்கள் சமையலறையில் உள்ளது.",
            "thali_title": "தினசரி தாலி பிளானர்",
            "thali_subtitle": "சீரான இந்திய உணவு முறை.",
            "thali_suggest": "தாலியை பரிந்துரைக்க",
            "thali_add_all": "தாலியை சந்தைப் பட்டியலில் சேர்க்க",
            "mandi_title": "காய்கறி சந்தை",
            "mandi_empty": "பட்டியல் காலியாக உள்ளது",
            "mandi_empty_sub": "பிடித்த செய்முறைகளில் இருந்து பொருட்களை சேர்க்கவும்.",
            "clear_checked": "முடித்ததை நீக்குக",
            "add_item": "பொருளைச் சேர்க்க",
            "cookmode_title": "ஸ்மார்ட் குக்கர் முறை",
            "whistle_counter": "குக்கர் விசில் கவுண்டர்",
            "tap_whistle": "விசில் தட்டவும்",
            "whistle_done": "விசில் முடிந்தது! அடுப்பை அணைக்கவும்.",
            "waiting_whistle": "விசிலுக்காக காத்திருக்கிறது...",
            "desi_timers": "சமையல் நேரக் குறிப்புகள்",
            "countertop_reader": "படி படியாக வாசிக்க",
            "step_of": "படி %d / %d",
            "next_step": "அடுத்த படி",
            "prev_step": "முந்தைய படி",
            "finished_cooking": "சமையல் முடிந்தது! 🎉",
            "settings": "சுயவிவரம் மற்றும் அமைப்புகள்",
            "theme": "கருப்பொருள் (டார்க் / லைட்)",
            "theme_system": "சிஸ்டம்",
            "theme_light": "லைட்",
            "theme_dark": "டார்க்",
            "language": "மொழி தேர்வு",
            "cloud_sync": "கிளவுட் ஒத்திசைவு (Google)",
            "sync_now": "ஒத்திசைக்க",
            "synced_status": "Google கணக்குடன் ஒத்திசைக்கப்பட்டது",
            "logout": "வெளியேறு"
        ],
        
        // 7. TELUGU (తెలుగు)
        "te": [
            "tab_cookbook": "వంటల పుస్తకం",
            "tab_thali": "థాలీ ప్లానర్",
            "tab_groceries": "కూరగాయల మార్కెట్",
            "tab_cookmode": "వంట మోడ్",
            "scope_curated": "అందుబాటు వంటలు (400+)",
            "scope_my_kitchen": "నా వంటగది",
            "diet_all": "అన్నీ",
            "diet_veg": "శాకాహారం",
            "diet_non_veg": "మాంసాహారం",
            "search_placeholder": "వంటకాలు, పదార్థాలు వెతకండి...",
            "filter_cuisine": "వంటకం శైలి",
            "filter_meal": "భోజన సమయం",
            "filter_category": "వర్గం",
            "filter_reset": "రీసెట్",
            "aaj_kya_banau": "ఈరోజు ఏం వండాలి?",
            "aaj_kya_banau_sub": "ఏం వండాలో తోచట్లేదా? వెంటనే సలహా పొందండి.",
            "aaj_kya_banau_btn": "కొత్త సలహా!",
            "btn_import_video": "రీల్స్ / షార్ట్స్ నుండి పొందండి",
            "btn_add_manual": "కొత్త వంటకాన్ని చేర్చండి",
            "ingredients": "కావలసిన పదార్థాలు",
            "instructions": "వండే విధానం",
            "add_all_to_groceries": "లిస్టులో చేర్చండి",
            "share_recipe": "వంటకాన్ని షేర్ చేయండి",
            "delete_recipe": "వంటకాన్ని తొలగించండి",
            "confirm_delete_title": "వంటకాన్ని తొలగించాలా?",
            "confirm_delete_msg": "ఈ వంటకం మీ వంటగది నుండి పూర్తిగా తొలగించబడుతుంది.",
            "cancel": "రద్దు",
            "delete": "తొలగించు",
            "already_in_kitchen": "ఇప్పటికే సేవ్ చేయబడింది",
            "already_in_kitchen_msg": "ఈ వీడియో వంటకం ఇప్పటికే మీ వద్ద ఉంది.",
            "thali_title": "రోజువారీ థాలీ ప్లానర్",
            "thali_subtitle": "సమతుల్య భారతీయ భోజనం.",
            "thali_suggest": "థాలీ సూచించండి",
            "thali_add_all": "మొత్తం థాలీని లిస్టులో చేర్చండి",
            "mandi_title": "కూరగాయల మార్కెట్",
            "mandi_empty": "మీ లిస్టు ఖాళీగా ఉంది",
            "mandi_empty_sub": "వంటకాల నుండి కావలసినవి చేర్చండి.",
            "clear_checked": "కొన్నవి తీసివేయండి",
            "add_item": "వస్తువును చేర్చండి",
            "cookmode_title": "స్మార్ట్ కుక్ మోడ్",
            "whistle_counter": "కుక్కర్ విజిల్ కౌంటర్",
            "tap_whistle": "విజిల్ నొక్కండి",
            "whistle_done": "విజిల్స్ పూర్తయ్యాయి! స్టవ్ ఆపండి.",
            "waiting_whistle": "విజిల్ కోసం వేచిచూస్తున్నారు...",
            "desi_timers": "వంట టైమర్లు",
            "countertop_reader": "దశల వారీగా వంట",
            "step_of": "దశ %d / %d",
            "next_step": "తదుపరి దశ",
            "prev_step": "మునుపటి దశ",
            "finished_cooking": "వంట పూర్తయింది! 🎉",
            "settings": "ప్రొఫైల్ & సెట్టింగ్‌లు",
            "theme": "థీమ్ (డార్క్ / లైట్)",
            "theme_system": "సిస్టమ్",
            "theme_light": "లైట్",
            "theme_dark": "డార్క్",
            "language": "భాషను ఎంచుకోండి",
            "cloud_sync": "క్లౌడ్ సింక్ (Google)",
            "sync_now": "ఇప్పుడే సింక్ చేయండి",
            "synced_status": "డేటా Google ఖాతాతో భద్రపరచబడింది",
            "logout": "లాగ్ అవుట్"
        ],
        
        // 8. BENGALI (বাংলা)
        "bn": [
            "tab_cookbook": "রান্নার বই",
            "tab_thali": "থালি প্ল্যানার",
            "tab_groceries": "সবজি মান্ডি",
            "tab_cookmode": "কুক মোড",
            "scope_curated": "ইনবিল্ট রেসিপি (400+)",
            "scope_my_kitchen": "আমার রান্নাঘর",
            "diet_all": "সব পদ",
            "diet_veg": "নিরামিষ",
            "diet_non_veg": "আমিষ",
            "search_placeholder": "রান্না, পনির, চিকেন, ডাল বা মশলা খুঁজুন...",
            "filter_cuisine": "রন্ধনশৈলী",
            "filter_meal": "খাবারের সময়",
            "filter_category": "বিভাগ",
            "filter_reset": "রিসেট",
            "aaj_kya_banau": "আজ কি রান্না হবে?",
            "aaj_kya_banau_sub": "ভাবতে পারছেন না? এখনই চটজলদি পরামর্শ নিন।",
            "aaj_kya_banau_btn": "নতুন পরামর্শ!",
            "btn_import_video": "রিলস / শর্টস থেকে রেসিপি আনুন",
            "btn_add_manual": "নতুন রেসিপি যোগ করুন",
            "ingredients": "প্রয়োজনীয় উপকরণ",
            "instructions": "রান্নার প্রণালী",
            "add_all_to_groceries": "সবজি মান্ডিতে যোগ করুন",
            "share_recipe": "রেসিপি শেয়ার করুন",
            "delete_recipe": "রেসিপি মুছুন",
            "confirm_delete_title": "রেসিপিটি মুছবেন?",
            "confirm_delete_msg": "এই রেসিপিটি আপনার রান্নাঘর থেকে মুছে যাবে।",
            "cancel": "বাতিল",
            "delete": "মুছুন",
            "already_in_kitchen": "আগে থেকেই সংরক্ষিত",
            "already_in_kitchen_msg": "এই ভিডিও রেসিপিটি আগেই আপনার রান্নাঘরে আছে।",
            "thali_title": "দৈনিক থালি প্ল্যানার",
            "thali_subtitle": "পরিপূর্ণ পুষ্টিকর সুস্বাদু ভারতীয় খাবার।",
            "thali_suggest": "থালি সাজান",
            "thali_add_all": "সম্পূর্ণ থালি তালিকায় যোগ করুন",
            "mandi_title": "সবজি মান্ডি",
            "mandi_empty": "আপনার তালিকা খালি",
            "mandi_empty_sub": "পছন্দের রেসিপি থেকে প্রয়োজনীয় উপকরণ যোগ করুন।",
            "clear_checked": "কেনা জিনিস মুছুন",
            "add_item": "জিনিস যোগ করুন",
            "cookmode_title": "স্মার্ট কুক মোড",
            "whistle_counter": "কুকার সিটি কাউন্টার",
            "tap_whistle": "সিটি গুনুন",
            "whistle_done": "সিটি শেষ! গ্যাস বন্ধ করুন।",
            "waiting_whistle": "কুকারের সিটির অপেক্ষা...",
            "desi_timers": "রান্নার টাইমার",
            "countertop_reader": "ধাপে ধাপে রান্নার গাইড",
            "step_of": "ধাপ %d / %d",
            "next_step": "পরের ধাপ",
            "prev_step": "আগের ধাপ",
            "finished_cooking": "রান্না সম্পন্ন! 🎉",
            "settings": "প্রোফাইল ও সেটিংস",
            "theme": "থিম (ডার্ক / লাইট)",
            "theme_system": "সিস্টেম",
            "theme_light": "লাইট",
            "theme_dark": "ডার্ক",
            "language": "ভাষা নির্বাচন",
            "cloud_sync": "ক্লাউড সিঙ্ক (Google)",
            "sync_now": "এখনই সিঙ্ক করুন",
            "synced_status": "Google অ্যাকাউন্টের সাথে সুরক্ষিত",
            "logout": "লগ আউট"
        ]
    ]
}
